# Generated by Django 3.2.8 on 2021-10-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_naame',
            new_name='first_name',
        ),
    ]
