# Generated by Django 3.2.8 on 2021-10-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_description', models.CharField(max_length=750)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('hotel_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('hotel_photo_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('hotel_photo_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('hotel_photo_3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('hotel_photo_4', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('amenities', models.ManyToManyField(to='hotels.Amenities')),
            ],
        ),
    ]
