# Generated by Django 3.2.8 on 2021-10-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
    ]
