# Generated by Django 3.2.8 on 2021-10-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20211015_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(choices=[('Beach View', 'Beach View'), ('Laundry service', 'Laundry service'), ('Salon', 'Salon'), ('Spa', 'Spa'), ('Restaurant', 'Restaurant'), ('Hot bath', 'Hot bath'), ('Nightclub / DJ', 'Nightclub / DJ'), ('Entertainment staff', 'Entertainment staff'), ('Bar / lounge', 'Bar / lounge'), ('Fitness Centre with Gym / Workout Room', 'Fitness Centre with Gym / Workout Room'), ('Pool', 'Pool'), ('Free High Speed Internet (WiFi)', 'Free High Speed Internet (WiFi)'), ('Free Parking', 'Free Parking')], max_length=100),
        ),
    ]
