# Generated by Django 3.2.8 on 2021-10-15 13:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Beach View', 'Beach View'), ('Laundry service', 'Laundry service'), ('Salon', 'Salon'), ('Spa', 'Spa'), ('Restaurant', 'Restaurant'), ('Hot bath', 'Hot bath'), ('Nightclub / DJ', 'Nightclub / DJ'), ('Entertainment staff', 'Entertainment staff'), ('Bar / lounge', 'Bar / lounge'), ('Fitness Centre with Gym / Workout Room', 'Fitness Centre with Gym / Workout Room'), ('Pool', 'Pool'), ('Free High Speed Internet (WiFi)', 'Free High Speed Internet (WiFi)'), ('Free Parking', 'Free Parking')], max_length=200),
        ),
    ]
