# Generated by Django 3.2.8 on 2021-10-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_hotel_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(choices=[('Hyderabad', 'HYD'), ('Mahabalipuram', 'MHA'), ('Vadodara', 'VAD')], default='Hyderabad', max_length=100),
        ),
    ]
