# Generated by Django 3.2.8 on 2021-10-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(choices=[('HYD', 'Hyderabad'), ('MHA', 'Mahabalipuram'), ('VAD', 'Vadodara')], max_length=100),
        ),
    ]
